// Generate the standalone-preview fallback from the extension's real catalogs.
const fs = require('node:fs');
const path = require('node:path');
const catalogs = Object.fromEntries(['en', 'zh_CN'].map(locale => [locale,
  JSON.parse(fs.readFileSync(path.join(__dirname, '_locales', locale, 'messages.json'), 'utf8'))]));
const source = `// Generated by build-locales.cjs; edit _locales/*/messages.json instead.
const shigangCatalogs = ${JSON.stringify(catalogs, null, 2)};
function shigangMessage(key, ...values) {
  const localized = globalThis.chrome?.i18n?.getMessage(key, values.map(String));
  if (localized) return localized;
  const language = document.documentElement.lang || navigator.language || 'en';
  const catalog = shigangCatalogs[/^zh/i.test(language) ? 'zh_CN' : 'en'];
  const entry = catalog[key] || shigangCatalogs.en[key];
  if (!entry) return key;
  return entry.message.replace(/\\$([a-zA-Z_]+)\\$/g, (_, name) => {
    const placeholder = entry.placeholders?.[name.toLowerCase()];
    return placeholder ? placeholder.content.replace(/\\$(\\d+)/g, (_, index) => String(values[Number(index) - 1] ?? '')) : '';
  });
}
`;
fs.writeFileSync(path.join(__dirname, 'localization.js'), source);
console.log('Built localization.js from English and Simplified Chinese catalogs');
