// Generated by build-locales.cjs; edit _locales/*/messages.json instead.
const shigangCatalogs = {
  "en": {
    "extensionName": {
      "message": "Shigang - ChatGPT Table of Contents"
    },
    "extensionShortName": {
      "message": "Shigang"
    },
    "extensionDescription": {
      "message": "Navigate long ChatGPT conversations with a table of contents, collapsible headings, math support, and a reading-follow sidebar."
    },
    "sidebarTitle": {
      "message": "Shigang · Outline"
    },
    "resizeLabel": {
      "message": "Resize outline width"
    },
    "closeLabel": {
      "message": "Close table of contents"
    },
    "organizing": {
      "message": "Organizing conversation…"
    },
    "navigationLabel": {
      "message": "Table of contents navigation"
    },
    "loading": {
      "message": "Loading…"
    },
    "following": {
      "message": "Follows your reading"
    },
    "autoWidth": {
      "message": "Auto width"
    },
    "resetWidth": {
      "message": "Reset to automatic width"
    },
    "toggleText": {
      "message": "Outline"
    },
    "openTitle": {
      "message": "Shigang · Open conversation outline"
    },
    "toggleLabel": {
      "message": "Toggle table of contents sidebar"
    },
    "crampedTitle": {
      "message": "Outline collapsed: not enough room. Widen the window or zoom out to open it."
    },
    "emptyResponses": {
      "message": "No responses found"
    },
    "emptyHeadings": {
      "message": "No headings in this response"
    },
    "promptLabel": {
      "message": "Prompt"
    },
    "newResponse": {
      "message": "New response"
    },
    "headingCount": {
      "message": "$COUNT$ headings",
      "placeholders": {
        "count": {
          "content": "$1"
        }
      }
    },
    "summary": {
      "message": "$RESPONSES$ responses · $HEADINGS$ headings",
      "placeholders": {
        "responses": {
          "content": "$1"
        },
        "headings": {
          "content": "$2"
        }
      }
    }
  },
  "zh_CN": {
    "extensionName": {
      "message": "拾纲 Shigang - ChatGPT 对话目录"
    },
    "extensionShortName": {
      "message": "拾纲"
    },
    "extensionDescription": {
      "message": "为 ChatGPT 长对话生成可折叠目录，支持标题跳转、数学公式、阅读跟随与深浅色侧栏。"
    },
    "sidebarTitle": {
      "message": "拾纲 · 对话目录"
    },
    "resizeLabel": {
      "message": "调整目录宽度"
    },
    "closeLabel": {
      "message": "关闭对话目录"
    },
    "organizing": {
      "message": "正在整理对话…"
    },
    "navigationLabel": {
      "message": "对话目录导航"
    },
    "loading": {
      "message": "正在加载…"
    },
    "following": {
      "message": "随正文跟随"
    },
    "autoWidth": {
      "message": "自动宽度"
    },
    "resetWidth": {
      "message": "恢复自动宽度"
    },
    "toggleText": {
      "message": "目录"
    },
    "openTitle": {
      "message": "拾纲 · 打开对话目录"
    },
    "toggleLabel": {
      "message": "展开或收起对话目录"
    },
    "crampedTitle": {
      "message": "右侧空间不足，目录已收起；扩大窗口或缩小页面后可展开"
    },
    "emptyResponses": {
      "message": "未找到回答"
    },
    "emptyHeadings": {
      "message": "这段回答没有标题"
    },
    "promptLabel": {
      "message": "问题"
    },
    "newResponse": {
      "message": "新回答"
    },
    "headingCount": {
      "message": "$COUNT$ 个标题",
      "placeholders": {
        "count": {
          "content": "$1"
        }
      }
    },
    "summary": {
      "message": "$RESPONSES$ 段回答 · $HEADINGS$ 个标题",
      "placeholders": {
        "responses": {
          "content": "$1"
        },
        "headings": {
          "content": "$2"
        }
      }
    }
  }
};
function shigangMessage(key, ...values) {
  const localized = globalThis.chrome?.i18n?.getMessage(key, values.map(String));
  if (localized) return localized;
  const language = document.documentElement.lang || navigator.language || 'en';
  const catalog = shigangCatalogs[/^zh/i.test(language) ? 'zh_CN' : 'en'];
  const entry = catalog[key] || shigangCatalogs.en[key];
  if (!entry) return key;
  return entry.message.replace(/\$([a-zA-Z_]+)\$/g, (_, name) => {
    const placeholder = entry.placeholders?.[name.toLowerCase()];
    return placeholder ? placeholder.content.replace(/\$(\d+)/g, (_, index) => String(values[Number(index) - 1] ?? '')) : '';
  });
}
